name: Tests and checks

on: 
  push:

jobs:
  tests:
    name: App tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        env:
          POETRY_VERSION: 1.8.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Format with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true

      - name: Typecheck with Pyright
        run: |
          pyright
        continue-on-error: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Tests with pytest
        run: |
          poetry run pytest tests
        env:
          WEB3_RPC_ENDPOINTS: ${{ secrets.WEB3_RPC_ENDPOINT }}
          NODE_OPERATOR_REGISTRY_ADDRESS: "0x595F64Ddc3856a3b5Ff4f4CC1d1fb4B46cFd2bAC"

